# Generated by Django 6.0.1 on 2026-01-09 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип пластика')),
                ('price_per_spool', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за катушку')),
                ('weight_g', models.IntegerField(verbose_name='Вес катушки (г)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название принтера')),
                ('power_consumption', models.IntegerField(verbose_name='Мощность (Вт)')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена покупки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrintOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_weight_g', models.IntegerField(verbose_name='Вес модели (г)')),
                ('print_time_hours', models.FloatField(verbose_name='Время печати (ч)')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.filament', verbose_name='Пластик')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.printer', verbose_name='Принтер')),
            ],
        ),
    ]
