# Generated by Django 6.0.1 on 2026-01-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_tariff', models.DecimalField(decimal_places=2, default=6.0, max_digits=5, verbose_name='Тариф (руб/кВт)')),
                ('markup_coefficient', models.DecimalField(decimal_places=2, default=2.5, max_digits=4, verbose_name='Коэффициент наценки')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
